examples/template.html, src/cells/base.js, src/cells/subcircuit.js, src/circuit.js
As requested in #1, this PR changes the serialization to and the deserialization from json to the cell's class names.
It also keeps backwards compatibility to yosys2digitaljs output by accepting both `type` or `celltype` in this priority order.
Fixes #1.
=> Serialization types

examples/template.html, src/index.js, src/style.css
As discussed in #4, this PR adds a fixed mode neither gates can be moved nor wires added. The mode can be set by `paper.fixed(boolean)`. You may try it using the "fixed mode" checkbox in the `template.html`.
Currently, the CSS rules feel kind of hacky as I still want to respond to mouseovers on gates where the displayed base (hex, dec etc.) may be changed or on subcircuits and memory to be able to open them in a popup window. Also clicks on inputs should be reacted on. I'm not sure if I even found all of the cases. Perhaps we could add some extra css class to the elements that still should respond to mouse events s.th. the rules would look nicer.
Also fixed mode is still not applied on subcircuit papers, for this to work the circuit itself should be aware of the fixed mode.
Do you have …
=> Add fixed mode on paper side

examples/fsm.json, src/cells/fsm.js, src/cells/memory.js, src/cells/subcircuit.js, src/index.js, webpack.config.js
This PR enables client-side webapps to handle subcircuits and memory content view freely by specifying a callback function at circuit initialization. If no callback is provided, the library defaults to the current behaviour (jQuery UI dialogs).
The containing div is automatically appended to `html > body` but can then be moved by webapps to different places to support e.g. tab view.
Fixes #6.
=> Decouple subwindow handling from core logic

src/circuit.js, src/index.js
This PR adds the possibility to use different or slightly changed cell classes by providing a custom cell namespace at circuit instantiation. Also export the standard cell namespace so that it is possible to simply add or override some of  the cell classes.
=> Support custom cell namespace

src/cells/base.js
In case `bits = 1`, the label's text is set to an empty string and jointJS automatically hides the label. This is a first move towards #2 allowing visual appearance change.
=> Always add bits label to ports markup

examples/template.html, src/cells/base.js, src/circuit.js
This PR adds a new optional argument to `toJSON()` to allow ignoring layout information while saving a circuit to json. Also adapts slightly the examples template to see the new behavior. For backward compatibility, it defaults to saving the layout information.
=> Allow ignoring layout information on serialization

examples/gates.json, src/cells/arith.mjs, src/cells/base.mjs, src/cells/bus.mjs, src/cells/dff.mjs, src/cells/fsm.mjs, src/cells/gates.mjs, src/cells/io.mjs, src/cells/memory.mjs, src/cells/mux.mjs, src/cells/subcircuit.mjs, src/circuit.mjs, src/index.mjs, src/style.css, webpack.config.js
This PR tries to simplify some of the core codebase by moving to the standard jointJS solution for ports, markup, initialization and styling (via `attrs`) and by using a slightly clearer gate hierarchy.
I'm aware this branch contains a lot of changed lines, but most of the changes are connected and could not be committed separately (e.g. `addPort` only works after the `constructor` has already been called). I will try to give a quick overview over the changes here, feel free to ask if something is unclear.
Fixes #13 by switching to the [standard jointJS port](https://resources.jointjs.com/docs/jointjs/v3.0/joint.html#dia.Element.ports) solutions and a second move forwards towards #2 as several properties can now be changed including the `bits` and (at least some of) the gates should react …
=> Refactor class hierarchy, markup and ports

src/cells/arith.mjs, src/cells/base.mjs, src/cells/bus.mjs, src/cells/gates.mjs, src/cells/io.mjs, src/cells/memory.mjs, src/cells/mux.mjs, src/cells/subcircuit.mjs, src/style.css
This PR fixes #23 in two steps:
- switching from classNames to [jointjs selectors](https://resources.jointjs.com/tutorial/custom-elements#markup) for default `attrs` styling ("Selectors are important for the targeting of subelements by element attributes. Although providing a selector to identify a subelement is not strictly required, it makes JointJS noticeably faster because it can avoid querying the DOM."). For my experiments this change did not produce any noticeable performance boost, but at least it ran as fast as before.
- Instead of toggling corresponding classes in the `View`s, temporary attributes (such as "high", "low" or "bus") are directly set on the element for each value change. The temporary attributes might be adapted by overwriting `this.attrs` inside the View.
As …
=> Move CSS styling to Javascript

src/cells/io.mjs
Fixes a bug introduced by #25 for port styling of Button and Lamp.
Before:
After:
=> Fix button/lamp port styling issue

examples/warnings.json, src/cells/base.mjs, src/cells/io.mjs, src/cells/subcircuit.mjs, src/circuit.mjs, src/index.mjs, webpack.config.js
As discussed in #10, a visual warning is shown for invalid connections (not matching bit-sizes) on the wires directly and in case of subcircuits, on the subcircuit box too. For now, there is no additional message shown as a tooltip, but this could potentially be added in a second step later.
See the newly added `warnings.json` example:
In case of warnings, the simulation will stop and prevent starting until all connections are valid.
The information is also accessible by code via `HeadlessCircuit.hasWarnings()`.
Also, I've moved some of the gate/wire update logic from the circuit level to the gates and wires themselves to better separate the code logically.
=> Visual warning and prevent simulation on badly connected wires

src/cells/base.mjs
As bit lines of size zero are [by definition](https://github.com/tilk/js_3vl/blob/master/src/index.ts#L597) high *and* low, but undefined, this PR reorders the coloring to properly reflect zero bit lines as undefined.
=> Show zero bits line as undefined instead of high

examples/template.html, src/cells/base.mjs, src/cells/bus.mjs, src/cells/io.mjs, src/circuit.mjs
Another step towards #2 consisting of:
- better warning message for unsupported property changes (now also resets the value)
- refactoring some code in `Gate` to group `input`/`outputSignals` changes together
- enhanced template for examples to (re)start simulation and play around with gates on the console
=> Fixes to change bits after initialization

src/cells/dff.mjs, src/cells/io.mjs
Fixes a bug introduced with #31.
=> Set undefined signal of correct bit width while instantiating NumEntry

src/cells/arith.mjs, src/cells/base.mjs, src/cells/bus.mjs, src/cells/dff.mjs, src/cells/fsm.mjs, src/cells/gates.mjs, src/cells/io.mjs, src/cells/memory.mjs, src/cells/mux.mjs, src/cells/subcircuit.mjs, src/circuit.mjs, src/index.mjs, tests/index.test.mjs
Also use new function syntax consistently.
This refactor has been tested with `npm run test` and (manually) by inspecting the examples.
Closes #33
=> Rename internal methods and fields to start with underscore

.gitignore, babel.config.json, package-lock.json, package.json, src/cells.mjs, src/cells/arith.mjs, src/cells/bus.mjs, src/cells/dff.mjs, src/cells/fsm.mjs, src/cells/gates.mjs, src/cells/memory.mjs, src/cells/mux.mjs, src/cells/subcircuit.mjs, src/circuit.mjs, src/index.mjs, src/iopanel.mjs, src/monitor.mjs
Changes include:
* Removing extension from local imports - allows 'require' to work after transpiling (mjs files become js files)
* Babel config for node target
* package.json changes:
* Change main to lib/circuit.js - for importing in nodejs
* Set browser field to previous main - for importing with bundler
* Export field to support importing ES6 modules in nodejs via [Conditional imports](https://nodejs.org/api/packages.html#packages_conditional_exports)
=> Support for importing digitaljs module to nodejs

package.json
Although its not specified in documentation, nodejs complains about conditional exports paths that do not start with "./" and refuses to import package. Changed main and browser paths for consistency.
=> Bugfix: Conditional exports paths

examples/gates.json, examples/io.json, src/cells/base.mjs, src/cells/io.mjs, src/cells/subcircuit.mjs, src/circuit.mjs, src/iopanel.mjs, webpack.config.js
As discussed in #35, this PR combines the three different input (Button/NumEntry/Input) and output (Lamp/NumDisplay/Output) types for better portability.
Things to consider:
- Boxes get currently only resized once upon initialization, not after manually changing e.g. bit width. As this same problem exists e.g. after renaming ports inside subcircuits, I would prefer working on this logic in a separate PR.
- For the Input/Output gates to know whether they are inside a subcircuit or not, the `subcircuit` property is already set on the (subcircuit) graph before adding the (subcircuit) gates. This will be most likely be refactored when working on #34 .
- The "public API" was slightly changed for `Input` and `Output` gates, the key methods are now called `setInput` and `getOutput` instead of …
=> Combine different io types

src/cells/base.mjs, src/index.mjs, src/tools.mjs
This enables re-use of code when using digitaljs as a library and changing appearance (e.g. leave out the "monitor" button on the wire tools).
=> Expose linkTools and default paperOptions for use outside of digitaljs

src/style.css
WebKit is the browser engine used by Safari and e.g. Midori on Linux. The issue is also present in the deployed version. I tested the change on WebKit, Chromium and Firefox, where it worked as expected.
I used the first answer from https://stackoverflow.com/questions/51313873/svg-foreignobject-not-working-properly-on-safari.
Before:
After:
=> Bugfix: foreignObject placement in WebKit (e.g. Safari)

src/cells/mux.mjs, src/cells/subcircuit.mjs, src/elkjs.mjs
It seems that the sporeOverlap algorithm does not touch the edges causing them to overlap
with the nodes. Switching back to the layered algorithm fixes this.
The combination of orthogonal edge routing and nodePlacement.favorStraightEdges
creates a layout fairly similar to the old one.
I've tried a few different combination, the orthorgonal edge seems to be the easiest
to convert between elkjs and jointjs. Using polyline edges isn't too bad visually either
but the result from jointjs would not match what elkjs produces.
Fix tilk/digitaljs_online#26
Screenshot of layout for the circuit in the original issue:
=> Layout edges using elsjs

src/cells/arith.mjs, src/transform.mjs, tests/index.test.mjs
The fix is limited to OpConst to make sure we can handle the deserialization without any problems. Also fixed the implementation of ShiftConst to handle BigInt produced by constant folding.
Add tests to check the validity and stability of the JSON object.
Fix #65
.... took me longer to add the tests than to fix the issue....
=> Make sure circuits with constant ops can be serialized to JSON correctly

src/cells/fsm.mjs, src/cells/io.mjs, src/cells/memory.mjs, src/cells/subcircuit.mjs
Prevent touch start events from being handled by jointjs to make sure
that the native click and focus events are generated.
It is still too easy to move some of the components with touch input but this should at least
make it possible to use touch interface to interact with the circuit.
Using touch as clicking works on all the browser variants I've tested, including firefox and chromium on linux, firefox (safari) on ipad, firefox and chrome on android. Using touch as hover, however, doesn't seem to work on the android browsers but that's most likely a separate issue...
=> Improve touch support

src/cells/io.mjs, tests/index.test.mjs
This is used in layout. Without saving this, the restored layout won't match the original
one since the port position on a subcircuit might have changed.
This happens with the `dff_masterslave.sv` example.
=> Save IO orders

src/elkjs.mjs
This matches the behavior of the dagre layout engine
and allows the user to distinguish between automatic and user-induced layout-change events.
This is particularly important since elkjs layout happens asynchronously so simply treating events from the initial display of the circuit as automatic layout event doesn't work.
=> Use batch to mark the beginning and end of elkjs layout change

src/index.mjs
This PR adds support for adding, removing and changing subcircuit buttons. An array of "Button" objects can be passed as an option to the constructor of a `Circuit` and will be applied to all subcircuit pop-ups. A button object currently looks like this:
```js
{
// unique button ID. Setting this to an existing ID overrides a previous button with the same ID.
id: string,
// (optional, default = false) Hides the button if `true`. Allows hiding existing buttons together with `id`.
hidden: boolean,
// The following two options are only relevant if the button is not hidden
// The text to display inside the button
buttonText: string,
// function taking the circuit, model and paper objects of the subcircuit
callback: ({circuit, model, paper}) => void
}
```
The current zoom in/out buttons are …
=> Add ability to change subcircuit buttons
